defaults:
  - _self_
  - algorithm: ddpg
  - memory: er
  - intrinsic: none
  - noise: white

memory:
  normalise_observation: True

seed: 0 
log:
  name: false
  wandb: false
  evaluation:
    evaluation_repeats: 1
    video:
      enable: false
      path: 
