seed: 0
env:
  name: "Pendulum-v1"
actor:
  features: 128
critic:
  features: 128
log:
  name: false
  frames_per_epoch: 100
  wandb: false
  evaluation:
    evaluation_repeats: 10
    video:
      enable: false
      frames_per_video: 10000
      path:
  checkpoint:
    enable: true
    frames_per_checkpoint: 10000
memory:
  capacity: 10000
train:
  initial_collection_size: 1000
  total_frames: 50000
  minibatch_size: 128
ddpg:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  target_update_frequency: 1
noise:
  scale: 0.1
  beta: 1

