defaults:
  - _self_
  - algorithm: ddpg
  - memory: er
  - intrinsic: none
  - noise: white

seed: 0
log:
  name: false
  wandb: false
  evaluation:
    evaluation_repeats: 10
    video:
      enable: false
      path: 
